### ISSUE TITLE
Need ability to set headers in a separate step

### ISSUE THREAD

**Issue by afoltin** [afoltin/garnishtest#10]
Something like this #1 : 

@Given("^the grppy request headers$")
    public void the_request_headers(@NonNull final Map<String, String> requestHeaders) {
        PREPARED_HEADERS.setValue(requestHeaders);
    }

    @When("^I call '(POST|PUT|PATCH)' on '(.+)' with JSON from '(.+)' and previously provided headers$")
    public void callMethodOnUrlWithJsonBodyAndHeaders(
            @NonNull final HttpMethod method,
            @NonNull final String url,
            @NonNull final String jsonReqBodyFile
    ) {
        String jsonBody = ClasspathUtils.loadFromClasspath(ResourceFilesVariables.getResourceFilesPrefix() + jsonReqBodyFile);

        jsonBody = ScenarioUserVariables.resolveInText(jsonBody, ValueEscapers.json());
        jsonBody = JsonUtils.makeValidJson(jsonBody);

        HttpRequestBuilder requestBuilder = this.httpClient.request(method, url);

        final Map<String, String> requestHeaders = PREPARED_HEADERS.getValue();
        if (requestHeaders != null) {
            for (final Map.Entry<String, String> entry : requestHeaders.entrySet()) {
                requestBuilder = requestBuilder.addHeader(entry.getKey(), entry.getValue());
            }
        }
         requestBuilder = requestBuilder.body(jsonBody, ContentType.APPLICATION_JSON);
        HttpResponse response = requestBuilder.execute();

        this.responseManager.setResponse(response);
    }

**Comment by cvmocanu** [comment]
will be fixed with #1
