### ISSUE TITLE
Header information in mock responses not being used

### ISSUE THREAD

**Issue by afoltin** [afoltin/garnishtest#7]
HttpMocksSteps.given_http_mocks_from_classpath_resource does not de-serialize header information for mock responses.

I got this to work using wiremock 2.5.0 
and the following code (no prizes for elegance here):

@Given("^http grppy mocks from \'(.+)\'$")
    public void given_http_mocks_from_classpath_resource(@NonNull String httpMocksFile) throws JSONException {
        if (httpMocksFile == null) {
            throw new IllegalArgumentException("httpMocksFile is null");
        } else {
            String serializedMappings = ClasspathUtils.loadFromClasspath(ResourceFilesVariables.getResourceFilesPrefix() + httpMocksFile);
            List<StubMapping> mappings = new ArrayList<>();
            JSONArray jsonArray = new JSONArray(serializedMappings);
            for (int i = 0; i < jsonArray.length(); i++) {
                mappings.add(StubMapping.buildFrom(jsonArray.getJSONObject(i).toString()));
            }

            this.httpMockServerManager.reset();
            this.httpMockServerManager.register(mappings);
        }
    }

**Comment by cvmocanu** [comment]
fixed in b557bc993b267ceab9869a4458d14d48360ef5bc
